language: python
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
cache:
    - pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"
    - "pypy"
    - "pypy3"
install:
    - pip install -r requirements-dev.txt
script:
    - python -m unittest discover
